version: '3.1'

services:
  gateway:
    build:
      context: ./gateway
    environment:
      TASKS: "http://tasks:80"
    ports:
      - "8000:80"
  tasks:
    build:
      context: ./backends/tasks
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_DB: dev_db
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: password
    ports:
      - 8001:80
  db:
    image: postgres
    environment:
      POSTGRES_DB: dev_db
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
  adminer:
    image: adminer
    ports:
      - 8080:8080
