version: '3.1'

services:
  tasks:
    build:
      context: ./backends/tasks
    environment:
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_DB: dev_db
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: password
    ports:
      - 8080:80
  db:
    image: postgres
    environment:
      POSTGRES_DB: dev_db
      POSTGRES_USER: dev
      POSTGRES_PASSWORD: password
    ports:
      - 5432:5432
