name: Upload image to Docker Hub
on:
  # Runs on pushes targeting the default branch
  push:
    branches: ["main"]

  # Allows you to run workflow manually from the Actions tab
  workflow_dispatch:

env:
  LATEST_TAG: oolong_front:latest

jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build and push container
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.LATEST_TAG }}
